# Chapter 3 Pandas

In [10]:
%load_ext watermark
%watermark -d -u -a "Duzhe Wang" -v -p numpy,pandas,matplotlib

The watermark extension is already loaded. To reload it, use:
  %reload_ext watermark
Duzhe Wang 
last updated: 2020-09-07 

CPython 3.8.1
IPython 7.12.0

numpy 1.18.1
pandas 1.0.1
matplotlib 3.1.3


In [5]:
import numpy as np
import pandas as pd

## Table of Contents

- [Introducing Pandas objects](#Introducing-Pandas-objects)
- [Data indexing and selection](#Data-indexing-and-selection)

## Introducing Pandas objects

- Three fundamental Pandas data structures: the ```Series```, ```DataFrame```, and ```Index```

### The Pandas series object

- A Pandas ```Series``` is a one-dimensional array of indexed data.

In [20]:
data=pd.Series([0.25, 0.5, 0.75, 1.0])

In [21]:
type(data)

pandas.core.series.Series

In [22]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [28]:
data[0]

0.25

In [29]:
data[1:3]

1    0.50
2    0.75
dtype: float64

- The ```Series``` wraps both a sequence of values and a sequence of indices, which we can access with the ```values``` and ```index``` attributes. 

In [24]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [27]:
data.index

RangeIndex(start=0, stop=4, step=1)

- While the NumPy array has an implicitly defined integer index used to access the values, the Pandas ```Series``` has an explicitly defined index associated with the values.

In [30]:
data=pd.Series([0.25, 0.5, 0.75, 1.0], index=["a", "b", "c", "d"])

In [31]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [32]:
data["b"]

0.5

In [34]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [35]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [75]:
data=pd.Series([0.25, 0.5, 0.75, 1.0], index=[2,5,3,7])

In [76]:
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [83]:
data[5]

0.5

In [80]:
data[7]

1.0

- Series as specialized dictionary

In [57]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}

In [58]:
population_dict

{'California': 38332521,
 'Texas': 26448193,
 'New York': 19651127,
 'Florida': 19552860,
 'Illinois': 12882135}

In [59]:
population_dict.keys()

dict_keys(['California', 'Texas', 'New York', 'Florida', 'Illinois'])

In [60]:
population_dict.values()

dict_values([38332521, 26448193, 19651127, 19552860, 12882135])

In [61]:
population=pd.Series(population_dict)

In [62]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [63]:
type(population)

pandas.core.series.Series

In [64]:
population.values

array([38332521, 26448193, 19651127, 19552860, 12882135])

In [65]:
population.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [66]:
population=pd.Series(population.values, index=population.index)

In [67]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [69]:
population["California":"Florida"]

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

- Constructing Series objects

```
>>> pd.Series(data, index=index)
```


In [84]:
pd.Series(5, index=[100,200,300])

100    5
200    5
300    5
dtype: int64

In [86]:
data=pd.Series({2:"a", 1:"b"})

In [87]:
data

2    a
1    b
dtype: object

In [88]:
data[2]

'a'

In [89]:
data[1]

'b'

In [90]:
data.values

array(['a', 'b'], dtype=object)

In [91]:
data.index

Int64Index([2, 1], dtype='int64')

In [94]:
pd.Series({2:"a", 1:"b", 3:"c"}, index=[3,2]) 
# note that in this case, the series is populated only with the explicitly defined keys

3    c
2    a
dtype: object

### The Pandas DataFrame object

- If a ```Series``` is an analog of a one-dimensional array with flexible indices, a ```DataFrame``` is an analog of a two-dimensional array with both flexible row indices and flexible column names. 

In [95]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}

In [96]:
area=pd.Series(area_dict)

In [97]:
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [98]:
state=pd.DataFrame({'population': population, 'area': area})

In [99]:
state

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [101]:
state.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [102]:
state.values

array([[38332521,   423967],
       [26448193,   695662],
       [19651127,   141297],
       [19552860,   170312],
       [12882135,   149995]])

In [103]:
state.columns

Index(['population', 'area'], dtype='object')

In [104]:
state["area"]

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [105]:
state["population"]

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: population, dtype: int64

In [118]:
state.loc["California", "population"]

38332521

- Constructing DataFrame objects

In [119]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [138]:
# From a single Series object
pd.DataFrame(population, columns=["population"])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [130]:
# From a list of dicts
data=[{"a": i, "b": 2*i} for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [131]:
data=[{"a": 1, "b":2}, {"b":3, "c":4}]
pd.DataFrame(data)

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [133]:
# From a dictionary of Series objects
pd.DataFrame({"population": population, "area": area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [136]:
# From a two-dimensional NumPy array
pd.DataFrame(np.random.rand(3,2), columns=["foo", "bar"], index=["a", "b", "c"])

foo       bar
a  0.992130  0.836362
b  0.879123  0.117289
c  0.316035  0.104460

### The Pandas index object

In [139]:
ind=pd.Index([2,3,5,7,11])

In [141]:
type(ind)

pandas.core.indexes.numeric.Int64Index

In [142]:
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [144]:
## index as immutable array
ind[1]

3

In [145]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [146]:
ind.size

5

In [147]:
ind.shape

(5,)

In [148]:
ind.ndim

1

In [149]:
ind.dtype

dtype('int64')

In [150]:
ind[1]=0

TypeError: Index does not support mutable operations

In [151]:
## index as ordered set
indA=pd.Index([1,3,5,7,9])
indB=pd.Index([2,3,5,7,11])

In [154]:
indA & indB  # intersection

Int64Index([3, 5, 7], dtype='int64')

In [155]:
indA | indB  # union

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [157]:
indA ^ indB  # symmetric difference

Int64Index([1, 2, 9, 11], dtype='int64')

## Data indexing and selection

- Data selection in Series

In [160]:
## Series as dictionary
data=pd.Series([0.25, 0.5, 0.75, 1.0], index=["a", "b", "c", "d"])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [161]:
data["b"]

0.5

In [163]:
"a" in data

True

In [164]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [169]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [171]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [172]:
## Series objects can be modified with a dictionary-like syntax. 
data["e"]=1.25

In [173]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [174]:
## Series as one-dimensional array

data["a":"c"]

a    0.25
b    0.50
c    0.75
dtype: float64

In [175]:
data[0:2]

a    0.25
b    0.50
dtype: float64

In [176]:
data[(data>0.3)&(data<0.8)]

b    0.50
c    0.75
dtype: float64

In [178]:
data[['a', "e"]]

a    0.25
e    1.25
dtype: float64

- Indexers: loc, iloc
  - ```loc``` attribute allows indexing and slicing that always references the explicit index
  - ```iloc``` attribute allows indexing and slicing that always references the implicit Python-style index
    

In [186]:
data=pd.Series(["a", "b", "c"], index=[1,3,5])

In [187]:
data

1    a
3    b
5    c
dtype: object

In [188]:
data.loc[1]

'a'

In [189]:
data.loc[1:3]

1    a
3    b
dtype: object

In [190]:
data.iloc[1]

'b'

In [191]:
data.iloc[1:3]

3    b
5    c
dtype: object

- Data selection in DataFrame

In [192]:
## DataFrame as a dictionary

area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data=pd.DataFrame({"area": area, "pop": pop})

In [193]:
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [194]:
data["area"]

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [200]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [201]:
data["pop"]

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: pop, dtype: int64

In [202]:
data["density"]=data["pop"]/data["area"]

In [203]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [204]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [209]:
data.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [213]:
data.keys()

Index(['area', 'pop', 'density'], dtype='object')

In [214]:
data.columns

Index(['area', 'pop', 'density'], dtype='object')

In [215]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [218]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [219]:
data.values[0,1]

38332521.0

In [220]:
data["area"]

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [221]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [222]:
data.loc[:"Illinois", :"pop"]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [223]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [234]:
data.loc["California"]

area       4.239670e+05
pop        3.833252e+07
density    9.041393e+01
Name: California, dtype: float64

In [235]:
data.loc["California", "pop"]

38332521

In [236]:
data.loc[data.density>100, ["pop", "density"]]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [239]:
data["Florida":"Illinois"]  # indexing refers to columns, slicing refers to rows

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [240]:
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [242]:
data[data["density"]>100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121