# Chapter 3 Pandas

In [10]:
%load_ext watermark
%watermark -d -u -a "Duzhe Wang" -v -p numpy,pandas,matplotlib

The watermark extension is already loaded. To reload it, use:
  %reload_ext watermark
Duzhe Wang 
last updated: 2020-09-07 

CPython 3.8.1
IPython 7.12.0

numpy 1.18.1
pandas 1.0.1
matplotlib 3.1.3


In [5]:
import numpy as np
import pandas as pd

## Introducing Pandas objects

### The Pandas series object

- A Pandas ```Series``` is a one-dimensional array of indexed data.

In [20]:
data=pd.Series([0.25, 0.5, 0.75, 1.0])

In [21]:
type(data)

pandas.core.series.Series

In [22]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [28]:
data[0]

0.25

In [29]:
data[1:3]

1    0.50
2    0.75
dtype: float64

- The ```Series``` wraps both a sequence of values and a sequence of indices, which we can access with the ```values``` and ```index``` attributes. 

In [24]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [27]:
data.index

RangeIndex(start=0, stop=4, step=1)

- While the NumPy array has an implicitly defined integer index used to access the values, the Pandas ```Series``` has an explicitly defined index associated with the values.

In [30]:
data=pd.Series([0.25, 0.5, 0.75, 1.0], index=["a", "b", "c", "d"])

In [31]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [32]:
data["b"]

0.5

In [34]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [35]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [75]:
data=pd.Series([0.25, 0.5, 0.75, 1.0], index=[2,5,3,7])

In [76]:
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [83]:
data[5]

0.5

In [80]:
data[7]

1.0

- Series as specialized dictionary

In [57]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}

In [58]:
population_dict

{'California': 38332521,
 'Texas': 26448193,
 'New York': 19651127,
 'Florida': 19552860,
 'Illinois': 12882135}

In [59]:
population_dict.keys()

dict_keys(['California', 'Texas', 'New York', 'Florida', 'Illinois'])

In [60]:
population_dict.values()

dict_values([38332521, 26448193, 19651127, 19552860, 12882135])

In [61]:
population=pd.Series(population_dict)

In [62]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [63]:
type(population)

pandas.core.series.Series

In [64]:
population.values

array([38332521, 26448193, 19651127, 19552860, 12882135])

In [65]:
population.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [66]:
population=pd.Series(population.values, index=population.index)

In [67]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [69]:
population["California":"Florida"]

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

- Constructing Series objects

```
>>> pd.Series(data, index=index)
```


In [84]:
pd.Series(5, index=[100,200,300])

100    5
200    5
300    5
dtype: int64

In [86]:
data=pd.Series({2:"a", 1:"b"})

In [87]:
data

2    a
1    b
dtype: object

In [88]:
data[2]

'a'

In [89]:
data[1]

'b'

In [90]:
data.values

array(['a', 'b'], dtype=object)

In [91]:
data.index

Int64Index([2, 1], dtype='int64')

In [94]:
pd.Series({2:"a", 1:"b", 3:"c"}, index=[3,2]) 
# note that in this case, the series is populated only with the explicitly defined keys

3    c
2    a
dtype: object

### The Pandas DataFrame object

- If a ```Series``` is an analog of a one-dimensional array with flexible indices, a ```DataFrame``` is an analog of a two-dimensional array with both flexible row indices and flexible column names. 

In [95]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}

In [96]:
area=pd.Series(area_dict)

In [97]:
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [98]:
state=pd.DataFrame({'population': population, 'area': area})

In [99]:
state

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [101]:
state.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [102]:
state.values

array([[38332521,   423967],
       [26448193,   695662],
       [19651127,   141297],
       [19552860,   170312],
       [12882135,   149995]])

In [103]:
state.columns

Index(['population', 'area'], dtype='object')

In [104]:
state["area"]

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [105]:
state["population"]

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: population, dtype: int64

In [118]:
state.loc["California", "population"]

38332521

- Constructing DataFrame objects

In [119]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [138]:
# From a single Series object
pd.DataFrame(population, columns=["population"])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [130]:
# From a list of dicts
data=[{"a": i, "b": 2*i} for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [131]:
data=[{"a": 1, "b":2}, {"b":3, "c":4}]
pd.DataFrame(data)

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [133]:
# From a dictionary of Series objects
pd.DataFrame({"population": population, "area": area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [136]:
# From a two-dimensional NumPy array
pd.DataFrame(np.random.rand(3,2), columns=["foo", "bar"], index=["a", "b", "c"])

foo       bar
a  0.992130  0.836362
b  0.879123  0.117289
c  0.316035  0.104460

### The Pandas index object

In [139]:
ind=pd.Index([2,3,5,7,11])

In [141]:
type(ind)

pandas.core.indexes.numeric.Int64Index

In [142]:
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [144]:
## index as immutable array
ind[1]

3

In [145]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [146]:
ind.size

5

In [147]:
ind.shape

(5,)

In [148]:
ind.ndim

1

In [149]:
ind.dtype

dtype('int64')

In [150]:
ind[1]=0

TypeError: Index does not support mutable operations

In [151]:
## index as ordered set
indA=pd.Index([1,3,5,7,9])
indB=pd.Index([2,3,5,7,11])

In [154]:
indA & indB  # intersection

Int64Index([3, 5, 7], dtype='int64')

In [155]:
indA | indB  # union

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [157]:
indA ^ indB  # symmetric difference

Int64Index([1, 2, 9, 11], dtype='int64')

## Data indexing and selection

- Data selection in Series

In [160]:
## Series as dictionary
data=pd.Series([0.25, 0.5, 0.75, 1.0], index=["a", "b", "c", "d"])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [161]:
data["b"]

0.5

In [163]:
"a" in data

True

In [164]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [169]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [171]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [172]:
## Series objects can be modified with a dictionary-like syntax. 
data["e"]=1.25

In [173]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [174]:
## Series as one-dimensional array

data["a":"c"]

a    0.25
b    0.50
c    0.75
dtype: float64

In [175]:
data[0:2]

a    0.25
b    0.50
dtype: float64

In [176]:
data[(data>0.3)&(data<0.8)]

b    0.50
c    0.75
dtype: float64

In [178]:
data[['a', "e"]]

a    0.25
e    1.25
dtype: float64

- Indexers: loc, iloc
  - ```loc``` attribute allows indexing and slicing that always references the explicit index
  - ```iloc``` attribute allows indexing and slicing that always references the implicit Python-style index
    

In [186]:
data=pd.Series(["a", "b", "c"], index=[1,3,5])

In [187]:
data

1    a
3    b
5    c
dtype: object

In [188]:
data.loc[1]

'a'

In [189]:
data.loc[1:3]

1    a
3    b
dtype: object

In [190]:
data.iloc[1]

'b'

In [191]:
data.iloc[1:3]

3    b
5    c
dtype: object

- Data selection in DataFrame

In [192]:
## DataFrame as a dictionary

area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data=pd.DataFrame({"area": area, "pop": pop})

In [193]:
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [194]:
data["area"]

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [200]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [201]:
data["pop"]

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: pop, dtype: int64

In [202]:
data["density"]=data["pop"]/data["area"]

In [203]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [204]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [209]:
data.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [213]:
data.keys()

Index(['area', 'pop', 'density'], dtype='object')

In [214]:
data.columns

Index(['area', 'pop', 'density'], dtype='object')

In [215]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [218]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [219]:
data.values[0,1]

38332521.0

In [220]:
data["area"]

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [221]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [222]:
data.loc[:"Illinois", :"pop"]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [223]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [234]:
data.loc["California"]

area       4.239670e+05
pop        3.833252e+07
density    9.041393e+01
Name: California, dtype: float64

In [235]:
data.loc["California", "pop"]

38332521

In [236]:
data.loc[data.density>100, ["pop", "density"]]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [239]:
data["Florida":"Illinois"]  # indexing refers to columns, slicing refers to rows

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [240]:
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [242]:
data[data["density"]>100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

## Operating on data in Pandas  

### Ufuncs: index preservation

In [18]:
import pandas as pd
import numpy as np

In [19]:
rng=np.random.RandomState(42)
ser=pd.Series(rng.randint(0, 10, 4))

In [22]:
ser

0    6
1    3
2    7
3    4
dtype: int64

In [23]:
df=pd.DataFrame(rng.randint(0, 10, (3,4)), columns=["A", "B", "C", "D"])

In [24]:
df

A  B  C  D
0  7  2  5  4
1  1  7  5  1
2  4  0  9  5

In [28]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [31]:
np.sin(df*np.pi/4)

A         B         C             D
0 -7.071068e-01  1.000000 -0.707107  1.224647e-16
1  7.071068e-01 -0.707107 -0.707107  7.071068e-01
2  1.224647e-16  0.000000  0.707107 -7.071068e-01

### UFuncs: index alignment

In [32]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')

In [33]:
area

Alaska        1723337
Texas          695662
California     423967
Name: area, dtype: int64

In [34]:
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [35]:
population

California    38332521
Texas         26448193
New York      19651127
Name: population, dtype: int64

In [36]:
population/area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [38]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [39]:
A=pd.Series([2,4,6], index=[0,1,2])

In [40]:
A

0    2
1    4
2    6
dtype: int64

In [41]:
B=pd.Series([1,3,5], index=[1,2,3])

In [42]:
B

1    1
2    3
3    5
dtype: int64

In [43]:
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [46]:
A/B

0    NaN
1    4.0
2    2.0
3    NaN
dtype: float64

In [47]:
A.add(B)

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [48]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [50]:
A=pd.DataFrame(rng.randint(0, 20, (2,2)), columns=["A", "B"])

In [51]:
A

A   B
0  11  16
1   9  15

In [52]:
B=pd.DataFrame(rng.randint(0, 10, (3,3)), columns=["B", "A", "C"])

In [53]:
B

B  A  C
0  2  6  3
1  8  2  4
2  2  6  4

In [54]:
A+B

A     B   C
0  17.0  18.0 NaN
1  11.0  23.0 NaN
2   NaN   NaN NaN

In [55]:
A.add(B, fill_value=0)

A     B    C
0  17.0  18.0  3.0
1  11.0  23.0  4.0
2   6.0   2.0  4.0

In [70]:
fill=A.stack().mean()
fill

12.75

In [69]:
A.add(B, fill_value=fill)

A      B      C
0  17.00  18.00  15.75
1  11.00  23.00  16.75
2  18.75  14.75  16.75

### UFuncs: operations between DataFrame and Series

In [71]:
A=rng.randint(10, size=(3,4))

In [72]:
A

array([[8, 6, 1, 3],
       [8, 1, 9, 8],
       [9, 4, 1, 3]])

In [73]:
A[0]

array([8, 6, 1, 3])

In [74]:
A-A[0]

array([[ 0,  0,  0,  0],
       [ 0, -5,  8,  5],
       [ 1, -2,  0,  0]])

In [75]:
df=pd.DataFrame(A, columns=["Q", "R", "S", "T"])

In [76]:
df

Q  R  S  T
0  8  6  1  3
1  8  1  9  8
2  9  4  1  3

In [77]:
df-df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  0 -5  8  5
2  1 -2  0  0

In [85]:
df["R"]

0    6
1    1
2    4
Name: R, dtype: int64

In [87]:
df.subtract(df["R"], axis=0)

Q  R  S  T
0  2  0 -5 -3
1  7  0  8  7
2  5  0 -3 -1

In [88]:
halfrow=df.iloc[0,::2]

In [89]:
halfrow

Q    8
S    1
Name: 0, dtype: int64

In [90]:
df-halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1  0.0 NaN  8.0 NaN
2  1.0 NaN  0.0 NaN

## Handling missing data

- Missing data: null, NaN, NA

### ```None```: Pythonic missing data

In [91]:
vals1=np.array([1,None, 3,4])

In [92]:
vals1

array([1, None, 3, 4], dtype=object)

In [96]:
np.sum(vals1)

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [97]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

### ```NaN```: Missing numerical data

In [100]:
vals2=np.array([1,np.nan, 3,4])

In [101]:
vals2

array([ 1., nan,  3.,  4.])

In [102]:
vals2.dtype

dtype('float64')

In [103]:
1+np.nan

nan

In [104]:
0*np.nan

nan

In [105]:
vals2.sum()

nan

In [106]:
vals2.min()

nan

In [107]:
vals2.max()

nan

In [108]:
np.nansum(vals2)

8.0

In [109]:
np.nanmax(vals2)

4.0

In [110]:
np.nanmin(vals2)

1.0

### NaN and None in Pandas

- ```NaN``` and ```None``` both have their place, and Pandas is built to handle the two of them nearly interchangeably.  

In [111]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [113]:
x=pd.Series(range(2))

In [114]:
x

0    0
1    1
dtype: int64

In [115]:
x[0]=None

In [116]:
x

0    NaN
1    1.0
dtype: float64

### Operating on Null values

- ```isnull()```: generate a boolean mask indicating missing values
- ```notnull()```: opposite of ```isnull()```
- ```dropna()```: return a filtered version of the data
- ```fillna()```: return a copy of the data with missing values filled or imputed

In [119]:
data=pd.Series([1, np.nan, "hello", None])

In [120]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [135]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [136]:
data[data.isnull()]

1     NaN
3    None
dtype: object

In [137]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [138]:
data.dropna()

0        1
2    hello
dtype: object

In [141]:
df=pd.DataFrame([[1, np.nan, 2], 
                 [2, 3, 5],
                 [np.nan, 4, 6]])

In [142]:
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

We can not drop single values from a DataFrame. We can only drop full rows or full columns. By default, ```dropna()``` will drop all rows in which any null values is present. 

In [143]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [144]:
df.dropna(axis=1)

2
0  2
1  5
2  6

In [145]:
df.dropna(axis=0)

0    1  2
1  2.0  3.0  5

In [146]:
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [148]:
df[3]=np.nan

In [149]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [153]:
df.dropna(axis=1, how="all")

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [154]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [155]:
data=pd.Series([1, np.nan, 2, None, 3], index=list("abcde"))

In [156]:
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [157]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [159]:
data.fillna(method="ffill") # propagate the previous value forward

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [160]:
data.fillna(method="bfill")

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [161]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [162]:
df.fillna(method="ffill", axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

Note that if a previous value is not avaible during a forward fill, the NA value remains

## Hierarchical indexing 

### A multiply indexed series

- The bad way

In [6]:
import numpy as np
import pandas as pd

In [19]:
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]
pop=pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [8]:
pop[("California", 2000)]

33871648

In [10]:
pop[("California", 2000): ("Texas", 2000)]

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
dtype: int64

In [11]:
pop.index

Index([('California', 2000), ('California', 2010),   ('New York', 2000),
         ('New York', 2010),      ('Texas', 2000),      ('Texas', 2010)],
      dtype='object')

In [14]:
pop[[i for i in pop.index if i[1]==2010]]

(California, 2010)    37253956
(New York, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

- The better way: Pandas MultiIndex

In [20]:
index=pd.MultiIndex.from_tuples(index)

In [21]:
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [25]:
pop=pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

Here the first two columns of the Series representation show the multiple index values. 

In [26]:
pop[:, 2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

- MultiIndex as extra dimension

In [30]:
pop_df=pop.unstack()

In [31]:
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [33]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [35]:
pop_df=pd.DataFrame({"total":pop, "under18": [9267089, 9284094,
                                   4687374, 4318033,
                                   5906301, 6879014]})

In [36]:
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [39]:
f_u18=pop_df["under18"]/pop_df["total"]

In [40]:
f_u18

California  2000    0.273594
            2010    0.249211
New York    2000    0.247010
            2010    0.222831
Texas       2000    0.283251
            2010    0.273568
dtype: float64

In [41]:
pop_df["f_u18"]=f_u18

In [42]:
pop_df

total  under18     f_u18
California 2000  33871648  9267089  0.273594
           2010  37253956  9284094  0.249211
New York   2000  18976457  4687374  0.247010
           2010  19378102  4318033  0.222831
Texas      2000  20851820  5906301  0.283251
           2010  25145561  6879014  0.273568

In [43]:
f_u18.unstack()

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

## Methods of multiIndex creation

In [44]:
df=pd.DataFrame(np.random.rand(4,2), index=[["a", "a", "b", "b"], [1, 2,1,2]], columns=["data1", "data2"])

In [45]:
df

data1     data2
a 1  0.182697  0.080749
  2  0.574668  0.150034
b 1  0.509551  0.050521
  2  0.489145  0.451298

In [46]:
data = {('California', 2000): 33871648,
        ('California', 2010): 37253956,
        ('Texas', 2000): 20851820,
        ('Texas', 2010): 25145561,
        ('New York', 2000): 18976457,
        ('New York', 2010): 19378102}

In [47]:
data

{('California', 2000): 33871648,
 ('California', 2010): 37253956,
 ('Texas', 2000): 20851820,
 ('Texas', 2010): 25145561,
 ('New York', 2000): 18976457,
 ('New York', 2010): 19378102}

In [49]:
data=pd.Series(data)

In [52]:
data

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

- Explicit MultiIndex constructors

In [53]:
pd.MultiIndex.from_arrays([["a", "a", "b", "b"], [1,2,1,1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 1)],
           )

In [54]:
pd.MultiIndex.from_tuples([("a", 1), ("a", 2), ("b", 1), ("b", 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [55]:
pd.MultiIndex.from_product([["a", "b"], [1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [62]:
pd.MultiIndex(levels=[["a", "b"], [1,2]], 
              codes=[[0, 0, 1,1], [0, 1,0 ,1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

- MultiIndex level names

In [63]:
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [64]:
pop.index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [65]:
pop.index.names=["state", "year"]

In [67]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

- MultiIndex for columns

In [71]:
index=pd.MultiIndex.from_arrays([[2013, 2013, 2014, 2014], [1,2,1,2]], names=["year", "visit"])

In [72]:
index

MultiIndex([(2013, 1),
            (2013, 2),
            (2014, 1),
            (2014, 2)],
           names=['year', 'visit'])

In [73]:
columns=pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                     names=['subject', 'type'])

In [74]:
columns

MultiIndex([(  'Bob',   'HR'),
            (  'Bob', 'Temp'),
            ('Guido',   'HR'),
            ('Guido', 'Temp'),
            (  'Sue',   'HR'),
            (  'Sue', 'Temp')],
           names=['subject', 'type'])

In [75]:
data=np.round(np.random.randn(4,6), 1)

In [76]:
data

array([[ 0.6,  0.2,  0. , -0. , -1. ,  2.5],
       [ 0.4,  0.3, -0.1,  1.2, -2.5, -0.7],
       [ 0.6, -1.6, -0.5,  0.3,  0.9, -0.3],
       [ 0.2,  1.3,  1.4, -0.1,  0.2, -0.8]])

In [77]:
data[:,::2]*=10

In [78]:
data

array([[  6. ,   0.2,   0. ,  -0. , -10. ,   2.5],
       [  4. ,   0.3,  -1. ,   1.2, -25. ,  -0.7],
       [  6. ,  -1.6,  -5. ,   0.3,   9. ,  -0.3],
       [  2. ,   1.3,  14. ,  -0.1,   2. ,  -0.8]])

In [79]:
data+=37

In [80]:
data

array([[43. , 37.2, 37. , 37. , 27. , 39.5],
       [41. , 37.3, 36. , 38.2, 12. , 36.3],
       [43. , 35.4, 32. , 37.3, 46. , 36.7],
       [39. , 38.3, 51. , 36.9, 39. , 36.2]])

In [81]:
health_data=pd.DataFrame(data, index=index, columns=columns)

In [82]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      43.0  37.2  37.0  37.0  27.0  39.5
     2      41.0  37.3  36.0  38.2  12.0  36.3
2014 1      43.0  35.4  32.0  37.3  46.0  36.7
     2      39.0  38.3  51.0  36.9  39.0  36.2

In [83]:
health_data["Guido"]

type          HR  Temp
year visit            
2013 1      37.0  37.0
     2      36.0  38.2
2014 1      32.0  37.3
     2      51.0  36.9

In [85]:
health_data.loc[2013]

subject   Bob       Guido         Sue      
type       HR  Temp    HR  Temp    HR  Temp
visit                                      
1        43.0  37.2  37.0  37.0  27.0  39.5
2        41.0  37.3  36.0  38.2  12.0  36.3

# Indexing and slicing a MultiIndex

## Multiply indexed Series

In [86]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [87]:
type(pop)

pandas.core.series.Series

In [88]:
pop.index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           names=['state', 'year'])

In [89]:
pop[("California", 2000)]

33871648

In [90]:
pop["California"]

year
2000    33871648
2010    37253956
dtype: int64

In [91]:
pop.loc["California": "New York"]

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
dtype: int64

In [92]:
pop[:, 2000]

state
California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [93]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [94]:
pop>22000000

state       year
California  2000     True
            2010     True
New York    2000    False
            2010    False
Texas       2000    False
            2010     True
dtype: bool

In [95]:
pop[pop>22000000]

state       year
California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64

In [96]:
pop[["California", "Texas"]]

state       year
California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
dtype: int64

## Multiply indexed DataFrames

In [97]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      43.0  37.2  37.0  37.0  27.0  39.5
     2      41.0  37.3  36.0  38.2  12.0  36.3
2014 1      43.0  35.4  32.0  37.3  46.0  36.7
     2      39.0  38.3  51.0  36.9  39.0  36.2

In [98]:
health_data["Guido"]

type          HR  Temp
year visit            
2013 1      37.0  37.0
     2      36.0  38.2
2014 1      32.0  37.3
     2      51.0  36.9

In [106]:
health_data[("Guido","HR")]

year  visit
2013  1        37.0
      2        36.0
2014  1        32.0
      2        51.0
Name: (Guido, HR), dtype: float64

In [107]:
health_data.iloc[:2, :2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      43.0  37.2
     2      41.0  37.3

In [108]:
health_data.loc[:, ("Bob", "HR")]

year  visit
2013  1        43.0
      2        41.0
2014  1        43.0
      2        39.0
Name: (Bob, HR), dtype: float64

In [110]:
health_data["Bob", "HR"]

year  visit
2013  1        43.0
      2        41.0
2014  1        43.0
      2        39.0
Name: (Bob, HR), dtype: float64

In [115]:
idx=pd.IndexSlice
health_data.loc[idx[:, 1], idx[:, "HR"]]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      43.0  37.0  27.0
2014 1      43.0  32.0  46.0

# Rearranging Multi-Indices

## Stacking and unstacking indices

In [150]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [151]:
pop.unstack()

year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [152]:
pop.unstack(level=0)

state  California  New York     Texas
year                                 
2000     33871648  18976457  20851820
2010     37253956  19378102  25145561

In [153]:
pop.unstack(level=1)

year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

## Index setting and resetting

Another way to rearrange hierarchical data is to turn the index labels into columns. This can be done with the 
```reset_index``` method.

In [157]:
pop_flat=pop.reset_index(name="population")

In [158]:
pop_flat

state  year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561

In [163]:
pop_flat.set_index(["state", "year"])

population
state      year            
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

# Data aggregations on Multi-Indices

In [164]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      43.0  37.2  37.0  37.0  27.0  39.5
     2      41.0  37.3  36.0  38.2  12.0  36.3
2014 1      43.0  35.4  32.0  37.3  46.0  36.7
     2      39.0  38.3  51.0  36.9  39.0  36.2

In [165]:
data_mean=health_data.mean(level="year")

In [166]:
data_mean

subject   Bob        Guido         Sue       
type       HR   Temp    HR  Temp    HR   Temp
year                                         
2013     42.0  37.25  36.5  37.6  19.5  37.90
2014     41.0  36.85  41.5  37.1  42.5  36.45

In [168]:
data_mean.mean(axis=1, level="type")

type         HR       Temp
year                      
2013  32.666667  37.583333
2014  41.666667  36.800000

In [172]:
data_mean.T.mean(level="type").T

type         HR       Temp
year                      
2013  32.666667  37.583333
2014  41.666667  36.800000

# Combining datasets: concat and append

In [173]:
def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data={c:[str(c)+str(i) for i in ind] for c in cols}
    return pd.DataFrame(data, ind)
    

In [174]:
make_df("ABC", range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [177]:
class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)
    

# Recall: concatenation of NumPy arrays

In [178]:
x=[1,2,3]
y=[4,5,6]
z=[7,8,9]

In [179]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [183]:
x=[[1,2],
    [3,4]]
np.concatenate([x,x],axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

# Simple concatenation with ```pd.concat```

In [185]:
ser1=pd.Series(["A", "B", "C"], index=[1,2,3])
ser2=pd.Series(["D", "E", "F"], index=[4,5,6])

In [187]:
ser1

1    A
2    B
3    C
dtype: object

In [188]:
ser2

4    D
5    E
6    F
dtype: object

In [189]:
pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [191]:
df1=make_df("AB", [1,2])

In [192]:
df1

A   B
1  A1  B1
2  A2  B2

In [193]:
df2=make_df("AB", [3,4])

In [194]:
df2

A   B
3  A3  B3
4  A4  B4

In [195]:
pd.concat([df1, df2])

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

By default, the concatenation takes place row-wise within the DataFrame.

In [196]:
df3=make_df("AB", [0,1])

In [197]:
df3

A   B
0  A0  B0
1  A1  B1

In [198]:
df4=make_df("CD", [0,1])

In [199]:
df4

C   D
0  C0  D0
1  C1  D1

In [200]:
pd.concat([df3, df4])

A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1

In [201]:
pd.concat([df3, df4], axis=1)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

In [207]:
x=make_df("AB", [0, 1])

In [208]:
x

A   B
0  A0  B0
1  A1  B1

In [209]:
y=make_df("AB", [0,1])

In [210]:
y

A   B
0  A0  B0
1  A1  B1

In [211]:
pd.concat([x, y])

A   B
0  A0  B0
1  A1  B1
0  A0  B0
1  A1  B1

In [212]:
df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [3, 4])

In [213]:
df5

A   B   C
1  A1  B1  C1
2  A2  B2  C2

In [214]:
df6

B   C   D
3  B3  C3  D3
4  B4  C4  D4

In [216]:
pd.concat([df5, df6])

A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

In [217]:
pd.concat([df5, df6], join="inner")

B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

## The ```append()``` method

In [218]:
df1


A   B
1  A1  B1
2  A2  B2

In [219]:
df2

A   B
3  A3  B3
4  A4  B4

In [220]:
df1.append(df2)

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

The ```append()``` method in Pandas does not modify the original object-instead it creates a new object 
with the combined data.