# Aggregations: min, max, and everything in between

- Summing the values in an array

In [2]:
import numpy as np
L=np.random.random(100)

In [3]:
sum(L)

51.782494430249066

In [4]:
np.sum(L)

51.78249443024909

In [6]:
big_array=np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)  # more quickly 

229 ms ± 4.69 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
522 µs ± 15.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


- Minimum and maximum

In [8]:
print(min(big_array))
print(max(big_array))

1.6004641030242794e-06
0.9999991695469148


In [9]:
print(np.min(big_array))
print(np.max(big_array))

1.6004641030242794e-06
0.9999991695469148


In [10]:
%timeit min(big_array)
%timeit np.min(big_array)

145 ms ± 1.42 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
512 µs ± 12.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


**Shorter syntax**:


In [11]:
big_array.min()

1.6004641030242794e-06

In [12]:
big_array.max()


0.9999991695469148

In [13]:
big_array.sum()

500458.69916716195

- Multi dimensional aggregates

In [14]:
M=np.random.random((3,4))

In [15]:
print(M)

[[0.37564793 0.15721977 0.43339754 0.51476876]
 [0.11843682 0.78251118 0.84051392 0.31755198]
 [0.01142494 0.10424082 0.08002212 0.69501367]]


In [17]:
M.sum()  # aggregate over the entire array

4.430749460895887

In [18]:
M.min(axis=0)   # within each column

array([0.01142494, 0.10424082, 0.08002212, 0.31755198])

In [24]:
M.max(axis=1)   # within each row

array([0.51476876, 0.84051392, 0.69501367])