# The basics of NumPy arrays 

## NumPy array attributes: ```ndim```, ```shape```, ```size```, ```dtype```, ```itemsize```, ```nbytes```

In [3]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1=np.random.randint(10, size=6)  # one-dimensional
x2=np.random.randint(10, size=(3,4))  # two-dimensional 
x3=np.random.randint(10, size=(3,4,5))  # three-dimensional 
print(x1)
print(x2)
print(x3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


Each array has attrbutes ```ndim```, ```shape```, and ```size```

In [5]:
print("x3 ndim:", x3.ndim)  # number of dimensions 
print("x3 shape:", x3.shape)  # size of each dimension
print("x3 size: ", x3.size) # total size of the array

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size:  60


Another useful attribute is the ```dtype```

In [7]:
print("dtype:", x3.dtype)

dtype: int64


Other attributes include ```itemsize```, which lists the size (in bytes) of each array element, and ```nbytes```, which lists the total size (in bytes) of the array. In general, we expect that nbytes is equal to itemsize times size.

In [9]:
print("itemsize:", x3.itemsize, "byptes")
print("nbytes:", x3.nbytes, "byptes")



itemsize: 8 byptes
nbytes: 480 byptes


## Array indexing: accessing single elements

In [13]:
x1

array([5, 0, 3, 3, 7, 9])

In [14]:
x1[0]

5

In [15]:
x1[4]

7

In [16]:
x1[-1]

9

In [17]:
x1[-2]

7

In [18]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [19]:
x2[0,0]

3

In [20]:
x2[2,0]

1

In [21]:
x2[2,-1]

7

In [22]:
x2[0,0]=12

In [23]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [26]:
x1[0]=3.14  # this will be truncated!

In [27]:
x1

array([3, 0, 3, 3, 7, 9])

## Array slicing: accesing subarrays

In [28]:
x=np.arange(10)

In [29]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
x[:5]

array([0, 1, 2, 3, 4])

In [32]:
x[5:] # elements after index 5

array([5, 6, 7, 8, 9])

In [33]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [34]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [35]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [37]:
x[::-1]  # all elements, reversed 

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [38]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

In [45]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [46]:
x2[:2, :3] 

array([[12,  5,  2],
       [ 7,  6,  8]])

In [48]:
x2[:3, ::2]  # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [50]:
x2[::-1, ::-1] # reversed together

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [52]:
x2[:,0]  # first column of x2

array([12,  7,  1])

In [53]:
x2[0, :] # first row of x2

array([12,  5,  2,  4])

<font color='blue'>
Subarrays as no-copy views: array slices return views rather than copies of the array data


    
    
    
    

In [63]:
print(x2)
x2_sub=x2[:2, :2]
print(x2_sub)
x2_sub[0,0]=99
print(x2)
    

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[[99  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


<font color='blue'>
Creating copies of arrays

In [65]:
x2_sub_copy=x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [66]:
x2_sub_copy[0,0]=42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [67]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [71]:
grid=np.arange(1,10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [72]:
x=np.array([1,2,3])
x.reshape((1,3))

array([[1, 2, 3]])

In [73]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [74]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [75]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Array concatenation and splitting

In [76]:
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [77]:
z=np.array([99,99,99])
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [78]:
gird=np.array([[1,2,3], [4,5,6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
x=np.array([1,2,3])
grid=np.array([[9,8,7], [6,5,4]])

In [82]:
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [83]:
y=np.array([[99], [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [84]:
x=np.array([1,2,3,99,99,3,2,1])

In [85]:
x1, x2,x3=np.split(x, [3,5])

In [88]:
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [92]:
grid=np.arange(16).reshape(4,4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [95]:
upper, lower=np.vsplit(grid, [2])

In [96]:
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [97]:
left, right=np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
