# Computation on NumPy arrays: Universal functions 


The key to making computation on NumPy arrays fast is to use vectorized operation, generally implemented 
through NumPy's universal functions.  


## The slowness of loops 

In [16]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output=np.empty(len(values))
    for i in range(len(values)):
        output[i]=1.0/values[i]
    return output

values=np.random.randint(1,10, size=5)
compute_reciprocals(values)


        
        

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [18]:
big_array=np.random.randint(1,100, size=1000000)
%timeit compute_reciprocals(big_array)

3.24 s ± 24.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Introducing UFuncs

In [20]:
print(compute_reciprocals(values))
print(1.0/values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [21]:
%timeit (1.0/big_array)

5.27 ms ± 169 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [22]:
print(np.arange(5))
print(np.arange(1,6))


[0 1 2 3 4]
[1 2 3 4 5]


In [23]:
np.arange(5)/np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [24]:
x=np.arange(9).reshape((3,3))

In [25]:
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [27]:
2**x  # power

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

## Exploring Numpy's UFuncs

Array arithmetic

In [31]:
x=np.arange(4)
print("x=",x)
print("x+5=", x+5)
print("x-5=", x-5)
print("x*2=", x*2)
print("x/2=", x/2)
print("x//2=", x//2) # floor division 
print("-x=", -x)
print("x**2=", x**2)
print("x%2=", x%2) # modulus

x= [0 1 2 3]
x+5= [5 6 7 8]
x-5= [-5 -4 -3 -2]
x*2= [0 2 4 6]
x/2= [0.  0.5 1.  1.5]
x//2= [0 0 1 1]
-x= [ 0 -1 -2 -3]
x**2= [0 1 4 9]
x%2= [0 1 0 1]


Absolute value: ```abs```, ```np.absolute```, ```np.abs```

In [32]:
x=np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

Trigonometric functions 

In [33]:
theta=np.linspace(0, np.pi, 3)

In [35]:
print("theta=", theta)
print("sin(theta)=", np.sin(theta))
print("cos(theta)=", np.cos(theta))
print("tan(theta)=", np.tan(theta))

theta= [0.         1.57079633 3.14159265]
sin(theta)= [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta)= [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta)= [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


Exponents and logarithms

In [39]:
x=np.array([1,2,3])
print("x=", x)
print("e^x=", np.exp(x))
print("2^x", np.exp2(x))
print("3^x", np.power(3,x))

x= [1 2 3]
e^x= [ 2.71828183  7.3890561  20.08553692]
2^x [2. 4. 8.]
3^x [ 3  9 27]


In [42]:
x=[1,2,4,10]
print("x=", x)
print("ln(x)=", np.log(x))
print("log2(x)=", np.log2(x))
print("log10(x)=", np.log10(x))

x= [1, 2, 4, 10]
ln(x)= [0.         0.69314718 1.38629436 2.30258509]
log2(x)= [0.         1.         2.         3.32192809]
log10(x)= [0.         0.30103    0.60205999 1.        ]


There are also some specialized versions that are useful for maintaining precision with very small input:

In [46]:
x=[0, 0.001, 0.01, 0.1]
print("exp(x)-1=", np.expm1(x))
print("log(1+x)=", np.log1p(x))

exp(x)-1= [0.         0.0010005  0.01005017 0.10517092]
log(1+x)= [0.         0.0009995  0.00995033 0.09531018]


Specialized ufuncs: use ```from scipy import special```

## Advanced Ufuncs features

Specifying output:

In [60]:
x=np.arange(5)
y=np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


Aggregates

In [69]:
x=np.arange(1,6)
np.add.reduce(x)

15

In [70]:
np.sum(x)

15

In [71]:
np.multiply.reduce(x)

120

In [72]:
np.product(x)

120

In [73]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [74]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

Outer products:

In [75]:
x=np.arange(1,6)
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])